packages:
  - "functions/*"

catalog:
  "@ai-sdk/openai-compatible": 1.0.0-beta.3
  "@ai-sdk/provider": 2.0.0-beta.1
  "@ai-sdk/provider-utils": 3.0.0-beta.2
  "@ai-sdk/react": 2.0.0-beta.9
  "@aws-sdk/client-sesv2": 3.777.0
  "@better-auth/cli": 1.3.7
  "@better-auth/stripe": 1.3.7
  "@cloudflare/vite-plugin": 1.12.4
  "@cloudflare/vitest-pool-workers": 0.8.71
  "@cloudflare/workers-types": 4.20250910.0
  "@cloudflare/actors": "0.0.1-beta.6"
  "@effect/language-service": 0.21.8
  "@epic-web/invariant": 1.0.0
  "@eslint/js": 9.35.0
  "@openauthjs/openauth": 0.4.3
  "@paralleldrive/cuid2": 2.2.2
  "@playwright/test": 1.55.0
  "@react-router/cloudflare": 7.9.1
  "@react-router/dev": 7.9.1
  "@react-router/fs-routes": 7.9.1
  "@standard-schema/spec": 1.0.0-beta.3
  "@tailwindcss/cli": 4.1.9
  "@tailwindcss/typography": 0.5.16
  "@tailwindcss/vite": 4.1.9
  "@types/node": 22.13.14
  "@types/react": 19.1.0
  "@types/react-dom": 19.1.2
  agents: 0.0.101
  ai: 5.0.0-beta.9
  aws4fetch: 1.0.20
  better-auth: 1.3.9
  class-variance-authority: 0.7.1
  effect: 3.16.12
  eslint: 9.35.0
  eslint-plugin-react: 7.37.5
  eslint-plugin-react-hooks: 5.2.0
  hono: 4.9.6
  isbot: 5.1.28
  jsonc-parser: 3.3.1
  lucide-react: 0.514.0
  openai: 5.8.2
  oxlint: 1.13.0
  playwright: 1.55.0
  radix-ui: 1.4.3
  react: 19.1.0
  react-aria-components: 1.11.0
  react-dom: 19.1.0
  react-markdown: 10.1.0
  react-router: 7.9.1
  remark-gfm: 4.0.1
  shadcn: 2.10.0
  sonner: 2.0.7
  stripe: 18.4.0
  tailwind-merge: 3.3.1
  tailwindcss: 4.1.9
  tw-animate-css: 1.3.4
  typescript: 5.9.2
  typescript-eslint: 8.43.0
  vite: 7.1.3
  vite-tsconfig-paths: 5.1.4
  vitest: 3.2.4
  workers-ai-provider: 0.7.1
  wrangler: 4.35.0
  zod: 4.1.5
  zx: 8.5.5
