packages:
  - "functions/*"

catalog:
  "@ai-sdk/openai": 1.3.22
  "@ai-sdk/react": 1.2.12
  "@aws-sdk/client-sesv2": 3.777.0
  "@cloudflare/vite-plugin": 1.6.0
  "@cloudflare/workers-types": 4.20250614.0
  "@effect/language-service": 0.21.8
  "@openauthjs/openauth": 0.4.3
  "@paralleldrive/cuid2": 2.2.2
  "@react-router/cloudflare": 7.6.2
  "@react-router/dev": 7.6.2
  "@react-router/fs-routes": 7.6.2
  "@standard-schema/spec": 1.0.0-beta.3
  "@tailwindcss/cli": 4.1.9
  "@tailwindcss/typography": 0.5.16
  "@tailwindcss/vite": 4.1.9
  "@types/node": 22.13.14
  "@types/react": 19.1.0
  "@types/react-dom": 19.1.2
  ai: 4.3.16
  aws4fetch: 1.0.20
  effect: 3.16.5
  hono: 4.7.11
  isbot: 5.1.28
  jsonc-parser: 3.3.1
  lucide-react: 0.514.0
  openai: 5.3.0
  oxlint: 1.1.0
  react: 19.1.0
  react-aria-components: 1.7.1
  react-dom: 19.1.0
  react-router: 7.6.2
  shadcn: 2.6.3
  stripe: 18.2.1
  tailwind-merge: 3.3.1
  tailwind-variants: 1.0.0
  tailwindcss: 4.1.9
  tw-animate-css: 1.3.4
  typescript: 5.8.2
  vite: 6.3.5
  vite-tsconfig-paths: 5.1.4
  workers-ai-provider: 0.6.1
  wrangler: 4.20.0
  zx: 8.5.5
